version: 2
jobs:
  build-deployer-image:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:patient0
        user:
          root # circleci cannot seem to get /var/run/docker.sock
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: |
          set -ex
          eval `aws ecr get-login --no-include-email --region $AWS_REGION`
          docker build -t circleci:deployer .circleci/images
          docker tag circleci:deployer 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
          docker push 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer

  ecs-up:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run: |
          set -ex
          ./ecs-up.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*circleci*"

  ecs-down:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -ex
          ./ecs-down.sh

workflows:
  version: 2
  gamut:
    jobs:
      - build-deployer-image
      - ecs-up:
          requires:
            - build-deployer-image
      - ecs-down:
          requires:
            - ecs-up
