version: 2
references:
  # sepp2k no way for array to contain anchor steps and additional steps

  jobs-gamut: &jobs-gamut
    jobs:
      - build-deployer-image
      - build-ecscli
      - ecs-up:
          requires:
            - build-deployer-image
            - build-ecscli
      - ecs-compose-up-except-dedupe:
          requires:
            - ecs-up
      - ecs-compose-up-dedupe:
          requires:
            - ecs-compose-up-except-dedupe
      - spider-newyork:
          requires:
            - ecs-compose-up-except-dedupe
      - spider-listingsproject:
          requires:
            - ecs-compose-up-except-dedupe
      - wait-for-digest:
          type: approval
          requires:
            - spider-newyork
            - spider-listingsproject
      - ecs-compose-down:
          type: approval
          requires:
            - wait-for-digest
      - ecs-down:
          requires:
            - ecs-compose-down


jobs:
  build-deployer-image:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:patient0
        user:
          root # circleci cannot seem to get /var/run/docker.sock
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: |
          set -x
          eval `aws ecr get-login --no-include-email --region $AWS_REGION`
          docker build --build-arg aws_region=${AWS_REGION} -t circleci:deployer .circleci/images
          docker tag circleci:deployer 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
          docker push 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer

  build-ecscli:
    docker:
      - image: circleci/golang:1.9.2
    steps:
      - run: |
          set -x
          # Thanks @bobziuchkovski
          git config --global url."https://${GIT_PASSWORD}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          mkdir -p /go/src/github.com/aws
          (cd /go/src/github.com/aws ; git clone -b my-branch https://github.com/dickmao/amazon-ecs-cli.git)
          # shlomi noach, code.openark.org
          (cd /go/src/github.com/aws/amazon-ecs-cli ; go get ./... && make)
      - save_cache:
          key: ecscli-{{ checksum "/go/src/github.com/aws/amazon-ecs-cli/.git/index" }}
          paths: 
            - /go/src/github.com/aws/amazon-ecs-cli

  ecs-up:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys: ecscli
      - run: |
          set -x
          ./ecs-up.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

  ecs-compose-up-except-dedupe:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys: ecscli
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          ./ecs-compose-up.sh -x dedupe
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

  ecs-compose-up-dedupe:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          source ./bash_aliases.sh
          for m in 0 1 ; do ssh-ecs $m touch /efs/var/lib/scrapyd/items/tutorial/newyork/digest ; done
          ./ecs-compose-up.sh -s dedupe

  spider-newyork:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          source ./bash_aliases.sh
          docke-ecs scrapyd-crawl scrapyd-client -t http://scrapyd:6800 schedule -p tutorial newyork
  
  spider-listingsproject: 
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          source ./bash_aliases.sh
          docke-ecs scrapyd-crawl scrapyd-client -t http://scrapyd:6800 schedule -p tutorial listingsproject

  wait-for-digest:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          source ./bash_aliases.sh
          inprog=0
          now=$(date +%s)
          while [ $inprog -lt 30 ] && ! ssh-ecs 0 find -L /efs/var/lib/scrapyd/items/tutorial/newyork/digest -newermt @$now | grep -q "." ; do sleep 30 ; let inprog=inprog+1 ; echo $inprog; done 

  ecs-compose-down:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys: ecscli
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          ./ecs-compose-down.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

  ecs-down:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -x
          ./ecs-down.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

workflows:
  version: 2
  commit:
    <<: *jobs-gamut
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "30 13 * * *"
          filters:
            branches:
              only: master
    <<: *jobs-gamut
