version: 2
jobs:
  build-deployer-image:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:patient0
        user:
          root # circleci cannot seem to get /var/run/docker.sock
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: |
          set -ex
          eval `aws ecr get-login --no-include-email --region $AWS_REGION`
          docker build -t circleci:deployer .circleci/images
          docker tag circleci:deployer 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
          docker push 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer

  build-ecscli:
    docker:
      - image: circleci/golang:1.9.2
    steps:
      - run: |
          set -ex
          # Thanks @bobziuchkovski
          git config --global url."https://${GIT_PASSWORD}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          mkdir -p /go/src/github.com/aws
          (cd /go/src/github.com/aws ; git clone -b my-branch https://github.com/dickmao/amazon-ecs-cli.git)
          # shlomi noach, code.openark.org
          (cd /go/src/github.com/aws/amazon-ecs-cli ; go get ./... && make)
      - save_cache:
          key: ecscli-{{ checksum "/go/src/github.com/aws/amazon-ecs-cli/.git/index" }}
          path: /go/src/github.com/aws/amazon-ecs-cli

  ecs-up:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys: ecscli
      - run: |
          set -ex
          ./ecs-up.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

  ecs-compose-up:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys: ecscli
      - attach_workspace:
          at: ecs-state
      - run: |
          set -ex
          ./ecs-compose-up.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

  ecs-compose-down:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -ex
          ./ecs-compose-down.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

  ecs-down:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:deployer
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - attach_workspace:
          at: ecs-state
      - run: |
          set -ex
          ./ecs-down.sh
      - persist_to_workspace:
          root: ecs-state
          paths:
            - "*"

workflows:
  version: 2
  gamut:
    jobs:
      - build-deployer-image
      - build-ecscli
      - ecs-up:
          requires:
            - build-deployer-image
            - build-ecscli
      - ecs-compose-up:
          requires:
            - ecs-up
      - ecs-compose-down:
          requires:
            - ecs-compose-up
      - ecs-down:
          requires:
            - ecs-compose-down
